### ISSUE TITLE
siteMetadata en gatsby-config.js

### ISSUE THREAD

**Issue by guillecro** [DemocraciaEnRed/democraciaos-landing-page#2]
Habria que poner que `url` es `democraciaos.org` y en algun momento tendriamos que poner una imagen (tengo entendido que estos son metatags en el `<head>` del html, no?

**Comment by sabriidelpoy** [comment]
Si! ahora actualizo la url

**Comment by sabriidelpoy** [comment]
Hice el fix: https://github.com/DemocraciaEnRed/democraciaOS-landing-page/commit/c96acaefc6b7f2c53c69296ee7b9334b1fd74f46
