### ISSUE TITLE
Cambio de texto

### ISSUE THREAD

**Issue by guillecro** [DemocraciaEnRed/democraciaos-landing-page#20]
Sacar _**instalarse e instalarse**_ aqui

![image](https://user-images.githubusercontent.com/8771166/77780963-87127c00-7033-11ea-972d-1e597ef2e5fc.png)

**Comment by sabriidelpoy** [comment]
@guillecro no me queda claro como quedaría el texto si saco esas palabras:

_Esto significa que el producto puede ~~instalarse e instalarse~~ de acuerdo a sus necesidades sin costo._

**Comment by guillecro** [comment]
Ahh, deberia ser solo "instalarse" jaja, perdon! @sabriidelpoy
